DROP DATABASE IF EXISTS dice_pizzaria;
CREATE database dice_pizzaria;

USE dice_pizzaria;

CREATE TABLE client (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	email VARCHAR(100),
	password VARCHAR(30),
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	address VARCHAR(255),
    address_2 VARCHAR(255),
    country VARCHAR(255),
    province VARCHAR(20),
	city VARCHAR(255),
	postal_code VARCHAR(6),
	phone VARCHAR(20),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE Table transactions (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	client_id int,
	email VARCHAR(100),
	first_name VARCHAR(255),
	last_name VARCHAR(255),
    status VARCHAR(20),
	isDelivery BOOLEAN,
	isPaid BOOLEAN,
	gross_total DECIMAL(10,2),
	tax_amount DECIMAL(10,2),
	net_total DECIMAL(10,2),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_info (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	transaction_id int,
	product_id int,
	addinfo VARCHAR(255),
	quantity int,
	order_price DECIMAL(10,2),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tax (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	province VARCHAR(2),
	tax_rate DECIMAL(5,3),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	description VARCHAR(255),
	size VARCHAR(10),
	set_price DECIMAL(10,2),
	archive BOOLEAN,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE staff (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(100),
	password VARCHAR(30),
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	address VARCHAR(255),
	city VARCHAR(255),
	province VARCHAR(2),
	postal_code VARCHAR(6),
	phone VARCHAR(20),
	role_id INT,
	manager_id INT,
	theme VARCHAR(20),
	units VARCHAR(8),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE timestamp (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	staff_id INT,
	checknum VARCHAR(3),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE timesheet (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	staff_id INT,
	workdays VARCHAR(255),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255),
	salary DECIMAL(10,2),
	department_id INT,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);